version: '3.8'

services:
  db:
    container_name: db_ramrobazar
    image: postgres
    restart: always
    # environment:
    #   - POSTGRES_DB=
    #   - POSTGRES_USER=
    #   - POSTGRES_PASSWORD=
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    # networks:
    #   - djangonetwork
  

  web:
    container_name: web_ramrobazar
    build:
      context: .
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    # links:
    #   - db:db
    # networks:
    #   - djangonetwork
    volumes: 
      - .:/usr/src/app
  
  
  esearch:
    container_name: search
    image: elasticsearch:7.14.2
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'



volumes:
  postgres_data:


# networks:
#   djangonetwork:
#     driver: bridge



# version: '3.8'

# services:
#   db:
#     container_name: db_ramrobazar
#     image: postgres
#     restart: always
#     environment:
#       - POSTGRES_DB=
#       - POSTGRES_USER=
#       - POSTGRES_PASSWORD=
#     ports:
#       - '5432:5432'