# Generated by Django 4.0 on 2022-08-10 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, unique, max-100', max_length=100, unique=True, verbose_name='brand name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='format: required, max_length=100', max_length=100, verbose_name='category name')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, underscore or hyphen', max_length=150, verbose_name='category url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='format: required, letters, numbers, underscore or hyphen', max_length=255, verbose_name='item url')),
                ('name', models.CharField(help_text='format: required, max_length=250', max_length=250, verbose_name='item name')),
                ('description', models.TextField(help_text='format: required', verbose_name='item description')),
                ('is_visible', models.BooleanField(default=True, help_text='format: true->product is visiible', verbose_name='item visibility')),
                ('is_blocked', models.BooleanField(default=False, help_text='format: true->product is blocked', verbose_name='item blocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date item was last updated')),
                ('show_price', models.DecimalField(decimal_places=2, help_text='format: max price = 99999.99', max_digits=7, verbose_name='Cost of Product shown on the site.')),
                ('sold_times', models.IntegerField(default=0, verbose_name='sold times')),
                ('location', models.TextField(blank=True, null=True, verbose_name='available locations')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='inventory.brand')),
                ('category', mptt.fields.TreeManyToManyField(to='inventory.Category')),
                ('reported_by', models.ManyToManyField(blank=True, related_name='reported_item', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='account.user')),
                ('users_wishlist', models.ManyToManyField(blank=True, related_name='user_wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False, help_text='format: default=false, true=item is sold', verbose_name='is the item sold?')),
                ('buyer_status', models.BooleanField(default=False, help_text='format: default=false, true=buyer confirms buying', verbose_name='bought by buyer')),
                ('seller_status', models.BooleanField(default=False, help_text='format: default=false, true=seller confirms selling', verbose_name='sold by seller')),
                ('sold_price', models.DecimalField(decimal_places=2, help_text='format: max price = 99999.99', max_digits=7, null=True, verbose_name='Price at which the item was sold.')),
                ('sold_units', models.IntegerField(default=0, help_text='number of units/times sold to buyer', null=True)),
                ('date_sold', models.DateField(help_text='date when item was sold', null=True, verbose_name='date sold')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.user')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sold_status', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_item.jpg', help_text='format: required, default-default_product.png', upload_to='items', verbose_name='item image')),
                ('alt_text', models.CharField(help_text='format: required, max-255', max_length=255, verbose_name='alternative text')),
                ('is_feature', models.BooleanField(default=False, help_text='format: default=false, true=default/main image', verbose_name='default/main image')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='inventory.item')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_commented', models.DateTimeField(auto_now_add=True, verbose_name='date commented')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='inventory.item')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='format: not required', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_children', to='inventory.comment', verbose_name='parent comment')),
            ],
            options={
                'ordering': ['-date_commented'],
            },
        ),
    ]
