# Generated by Django 4.0.4 on 2022-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='productsoldstatus',
            options={'verbose_name': 'product sold status', 'verbose_name_plural': 'product sold status'},
        ),
        migrations.AlterModelOptions(
            name='servicesoldstatus',
            options={'verbose_name': 'service sold status', 'verbose_name_plural': 'service sold status'},
        ),
        migrations.AddField(
            model_name='service',
            name='no_sold_times',
            field=models.IntegerField(default=0, verbose_name='No. of times service is sold'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_feature',
            field=models.BooleanField(default=False, help_text='format: default=false, true=default/main image', verbose_name='default/main image'),
        ),
    ]
