# Generated by Django 4.0.4 on 2022-05-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='format: true->service is blocked', verbose_name='service blocked'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='format: true->service is visiible', verbose_name='service visibility'),
        ),
    ]
