# Generated by Django 4.0 on 2022-06-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorservice',
            name='is_product',
            field=models.BooleanField(default=True, help_text='format: true->product, false->service', verbose_name='Is this product?'),
        ),
    ]
