# Generated by Django 4.0 on 2022-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='format: max price = 99999.99', max_digits=7, null=True, verbose_name='Maximum Cost of Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='format: max price = 99999.99', max_digits=7, null=True, verbose_name='Minimum Cost of Service'),
        ),
    ]
