# Generated by Django 4.0 on 2022-08-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldstatus',
            options={'verbose_name': 'Sold Status', 'verbose_name_plural': 'Sold Status'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, help_text='format: required, letters, numbers, underscore or hyphen', max_length=150, verbose_name='category url'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(editable=False, help_text='format: required, letters, numbers, underscore or hyphen', max_length=255, verbose_name='item url'),
        ),
    ]
