# Generated by Django 4.0 on 2022-08-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_soldstatus_options_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='alt_text',
            field=models.CharField(blank=True, help_text='format: required, max-255', max_length=255, null=True, verbose_name='alternative text'),
        ),
    ]
