# Generated by Django 4.0.4 on 2022-06-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productorservice_soldstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorservice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorservice',
            name='service',
        ),
    ]
