# Generated by Django 4.0.4 on 2022-06-06 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_remove_productorservice_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_or_service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.productorservice'),
        ),
        migrations.AddField(
            model_name='service',
            name='product_or_service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='inventory.productorservice'),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='format: Y-m-d H:M:S', verbose_name='date product/service created'),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='format: true->product is blocked', verbose_name='product/service blocked'),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='format: true->product is visiible', verbose_name='product/service visibility'),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='name',
            field=models.CharField(help_text='format: required, max_length=250', max_length=250, verbose_name='product/service name'),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_or_service', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='slug',
            field=models.SlugField(help_text='format: required, letters, numbers, underscore or hyphen', max_length=255, verbose_name='product/service url'),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='format: Y-m-d H:M:S', verbose_name='date product/service last updated'),
        ),
        migrations.AlterField(
            model_name='productorservice',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
