# Generated by Django 4.0 on 2022-10-21 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_remove_item_sold_times_remove_soldstatus_sold_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
