# Generated by Django 4.0 on 2022-10-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_reported_by_alter_item_users_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemDetail',
            new_name='ItemSpecification',
        ),
    ]
