# Generated by Django 4.0 on 2022-10-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_itemdetail_itemspecification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemspecification',
            options={'verbose_name': 'Item Specifications', 'verbose_name_plural': 'Item Specifications'},
        ),
        migrations.AlterField(
            model_name='itemspecification',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_specification', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(default='default_item.png', help_text='format: required, default-default_product.png', upload_to='items', verbose_name='item image'),
        ),
    ]
