# Generated by Django 4.0 on 2022-10-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_itemspecification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='format: default=false, true=comment is deleted.', verbose_name='is the comment deleted?'),
        ),
    ]
