# Generated by Django 4.0 on 2022-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_comment_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='format: true->product has been sold', verbose_name='item sold'),
        ),
    ]
