# Generated by Django 4.0 on 2022-10-29 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_alter_item_options_item_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='users_wishlist',
        ),
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='users_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
