# Generated by Django 4.0 on 2022-10-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_remove_item_users_wishlist_item_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='wishlist',
            new_name='users_wishlist',
        ),
    ]
