# Generated by Django 4.0 on 2022-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_contact_number',
            field=models.BooleanField(default=True),
        ),
    ]
